name: RecursiveItems
version: ${project.version}
main: net.wesjd.recursiveitems.RecursiveItems
depend: [Vault]
authors: [WesJD]
commands:
  sell:
    description: Opens sell items GUI
  setworth:

  worth:

  removeworth:

